### ISSUE TITLE
README issues

### ISSUE THREAD

**Issue by bshaffer** [google/php-photoslibrary#1]
There is a dead link to samples on the README page (under `review the samples`), and the sample itself is missing some key components, such as `php` syntax in the code blocks, a `use` statement for the `PhotosLibraryClient` class, and an explanation for `$_SESSION['credentials']`.

I would submit a PR but my understanding is all of this is automatically generated. Or are the READMEs maintained separately? If so I can submit some fixes.

**Comment by jfschmakeit** [comment]
Thanks for filing the issue!
The README is actually written by us, so pull requests are definitely appreciated.

I have updated the README based on your feedback, so I'll close this one for now, but please reply if I missed anything.
