### ISSUE TITLE
Easily access credentials from browser

### ISSUE THREAD

**Issue by ghost** [google/php-photoslibrary#12]
I am using credentials.json file to access clientid, redirecturl, and so on. is it safe to use from json file, because we can access it from direct url

**Comment by jfschmakeit** [comment]
This client library uses the [Google Auth client library](https://github.com/googleapis/google-auth-library-php). The client secret configuration should only be visible to the PHP application and not your end users. 

For web server applications such as these, the client_secret.json must be **kept secret** and should not be publicly accessible. You can read more about this in the [Using OAuth 2.0 for Web Server Applications
](https://developers.google.com/identity/protocols/OAuth2WebServer#creatingcred) developer guide.
