### ISSUE TITLE
Fatal Error when calling methods on in PhotosLibraryClient class

### ISSUE THREAD

**Issue by bhatir** [google/php-photoslibrary#17]
I am getting the error below when calling any method on a PhotosLibraryClient object. I read on [stackoverflow](https://stackoverflow.com/questions/44049812/php-call-to-undefined-function-bccomp) that this could be due to a missing bcmath extension but enabling this (via composer) did not help. 

_Fatal error: Uncaught Error: Call to undefined function Google\Protobuf\Internal\bccomp() in /app/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php:933 Stack trace: #0 /app/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(1218): Google\Protobuf\Internal\Message->convertJsonValueToProtoValue('1242', Object(Google\Protobuf\Internal\FieldDescriptor)) #1 /app/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(1167): Google\Protobuf\Internal\Message->mergeFromArrayJsonImpl(Array) #2 /app/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(815): Google\Protobuf\Internal\Message->mergeFromJsonArray(Array) #3 /app/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(1218): Google\Protobuf\Internal\Message->convertJsonValueToProtoValue(Array, Object(Google\Protobuf\Internal\FieldDescriptor)) #4 /app/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(1167): Google\Protobuf\Internal\Message->mergeFromArrayJsonImpl(Array) #5 /app/vendor/google/protobuf/src/ in /app/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php on line 933_

**Comment by jfschmakeit** [comment]
Yes, it looks like your PHP installation is missing the `bcmath` extension. I believe this needs to be loaded by your PHP interpreter and installed natively on your system.

The installations steps depend on your system, but on a deb-based Linux system, you could do `sudo apt-get install php-bcmath` for example. A lot of installations should also include this by default. (See also the manual for this module: https://www.php.net/manual/en/book.bc.php )
