### ISSUE TITLE
Please fix creation_time

### ISSUE THREAD

**Issue by VanPhongIT** [google/php-photoslibrary#3]
When $photosLibraryClient->batchCreateMediaItems($newMediaItems, ['albumId' => $albumId]);

Error:
vendor/google/gax/src/ApiCore/Transport/RestTransport.php:153
Error occurred during parsing: String specified for bool or submessage field: creation_time

**Comment by jfschmakeit** [comment]
Are you seeing this error when running the sample app?

I haven't been able to replicate this. What exactly are the parameters that you provide for the call? Could you share a longer code snippet?

Please also make sure that you are using the latest version of the library and that all of your composer dependencies are uptodate.
