### ISSUE TITLE
Picker API

### ISSUE THREAD

**Issue by kawax** [google/php-photoslibrary#35]
Updates to the Photo Library API and the Picker API have been announced.
Will the Picker API be supported in this package?
https://developers.googleblog.com/en/google-photos-picker-api-launch-and-library-api-updates/

**Comment by chrisachard** [comment]
This package will not support the Picker API because the Picker API is a REST API, while this package only supports the RPC endpoints for the Library API. The remaining Library API endpoints will continue to be supported.
