### ISSUE TITLE
pageSize has no effect ?

### ISSUE THREAD

**Issue by t301000** [google/php-photoslibrary#6]
Sorry for my poor english.

I downloaded sample from this repo, and change line 36 of albums/index.php

from
$pagedResponse = $photosLibraryClient->listAlbums();

to
$pagedResponse = $photosLibraryClient->listAlbums(['pageSize' => '5']);

but i got all 58 albums back.

**Comment by jfschmakeit** [comment]
The parameter for `pageSize` must be an integer and not a string literal.

This code snippet works as expected:
```
$pagedResponse = $photosLibraryClient->listAlbums(['pageSize' => 5]);
```

**Comment by amdrade** [comment]
`$pagedResponse = $photosLibraryClient->searchMediaItems(['pageSize' => 5]);`

Not working. 

When making the request via REST API, the pageSize parameter is respected.

```
POST /v1/mediaItems:search HTTP/1.1
Host: photoslibrary.googleapis.com
Content-Type: application/json
Authorization: Bearer ya29.......
Content-Length: 116

{
    "albumId": "AOa8sh4dPelJYkY....",
    "pageSize": 3
}
```

Version: 1.7.0
