### ISSUE TITLE
Example code fails with error unsupported_grant_type

### ISSUE THREAD

**Issue by rekcuFniarB** [google/php-photoslibrary#7]
Trying to run example code from docs but it fails with this error:

```
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://oauth2.googleapis.com/token` resulted in a `400 Bad Request` response:
{
  "error": "unsupported_grant_type",
  "error_description": "Invalid grant_type: "
}
 in /media/G/BFHome/Projects/Web/GooglePhoto/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /media/G/BFHome/Projects/Web/GooglePhoto/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /media/G/BFHome/Projects/Web/GooglePhoto/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /media/G/BFHome/Projects/Web/GooglePhoto/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /media/G/BFHome/Projects/Web/GooglePhoto/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Pr in /media/G/BFHome/Projects/Web/GooglePhoto/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113
```

Code I've tried to run:
```php
<?php
require('vendor/autoload.php');

use Google\Auth\Credentials\UserRefreshCredentials;
use Google\Photos\Library\V1\PhotosLibraryClient;
use Google\Photos\Library\V1\PhotosLibraryResourceFactory;

$credentials = json_decode(file_get_contents('credentials.json'), true);
$credentials = $credentials['installed'];
$credentials['refresh_token'] = null; // fails with error "Missing required parameter: refresh_token" without setting it

$scopes = array(
    'https://www.googleapis.com/auth/photoslibrary.readonly',
    //'https://www.googleapis.com/auth/photoslibrary',
    'https://www.googleapis.com/auth/photoslibrary.sharing',
    'https://www.googleapis.com/auth/photoslibrary.appendonly',
    'https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata'
);

$authCredentials = new UserRefreshCredentials(
    /* Add your scope, client secret and refresh token here */
    $scopes,
    $credentials
);

$photosLibraryClient = new PhotosLibraryClient(['credentials' => $authCredentials]);

$newAlbum = PhotosLibraryResourceFactory::album("Example Album");

$createdAlbum = $photosLibraryClient->createAlbum($newAlbum);

$albumId = $createdAlbum->getId();
```

The error occurs when calling `$photosLibraryClient->createAlbum($newAlbum)`.

**Comment by jfschmakeit** [comment]
It looks like you are trying to use credentials that were set up for the "other" credentials type. For this library (and the PHP OAuth library used here), you should use the "web application" credential if you are building an interactive web application. You can initialize the OAuth credentials as shown here: https://github.com/google/php-photoslibrary/blob/dde4b9a031250e6dd0322179b11aeb920c1f0ae3/src/common/common.php#L75

For `UserRefreshCredentials` you should need to supply the `client_id`, `client_secret` and a `refresh_token`, in addition to the `scopes`.

Please also note that the Google Photos Library API does not support service accounts - your users need to authenticate with their account to use this API.

**Comment by rekcuFniarB** [comment]
> you should use the "web application" credential

I've tried "web" too with the same result. There is no difference in credentials.json except redirect_uri (I used http://localhost/googlephoto/ for testing as docs suggest).

> if you are building an interactive web application.

No, it's going to be a CLI util but I tried running from web server too.

> For `UserRefreshCredentials` you should need to supply the `client_id`, `client_secret` and a `refresh_token`, in addition to the `scopes`.

But there is no `refresh_token` in the `credentials.json` file I got. When calling `UserRefreshCredentials` shouldn't it get and apply `refresh_token` automatically? I took a look into `UserRefreshCredentials`, it calls `OAuth` itself.

**Comment by rekcuFniarB** [comment]
OK, I could make it work doing as in `common.php`. Thanks for explanation.

But the docs need to be updated though.

**Comment by jmpozzo** [comment]
Anyone know how to use google service acount in this api. I need search my album's and use the content in my website.
Thanks!!

**Comment by jfschmakeit** [comment]
@jmpozzo Service accounts are not supported by the Google Photos Library API - see: https://developers.google.com/photos/library/guides/authorization#service-accounts
