### ISSUE TITLE
InvalidArgumentException with guzzlehttp dependency

### ISSUE THREAD

**Issue by sookoll** [google/php-photoslibrary#8]
Error message is clear:
```
InvalidArgumentException: Passing in the "body" request option as an array to send a POST request has been deprecated. Please use the "form_params" request option to send a application/x-www-form-urlencoded request, or the "multipart" request option to send a multipart/form-data request. 
```

Please update library.

EDIT: ok, it is more google/gax issue than this one, but media uploading is broken currently.

**Comment by jfschmakeit** [comment]
I haven't been able to replicate this issue using the PHP sample code and the latest version of this library and its dependencies.

How did you call the library to upload the file? What kind of file did you reference in the call? (What type/encoding/format was the file?)
Thanks!

**Comment by sookoll** [comment]
Wooh, it was nearly 2 months ago... Possible, that google/gax has fixed the error already. I was uploading jpg image. This was due to use of Guzzle 6.x while use case is for Guzzle < 6.0.
Instead of body param, must use form_params. But I don't have time currently to test, is it fixed.

**Comment by jfschmakeit** [comment]
No worries, in that case I'll close this one for now, but we'll keep an eye out if it anything similar comes up again.
(We had a few gax-related issues that had been resolved in the meantime.)
